# Generated by Django 4.2.2 on 2023-06-27 19:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CryptoCurrency",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("meta", models.JSONField(default=dict)),
                ("name", models.CharField(max_length=250, unique=True)),
                ("price", models.FloatField()),
                ("last_hour_difference", models.FloatField()),
                ("last_24_hour_difference", models.FloatField()),
                ("last_7_day_difference", models.FloatField()),
                ("market_cap", models.CharField(max_length=250)),
                ("volume_last_24_hour", models.CharField(max_length=250)),
                ("circulating_supply", models.CharField(max_length=250)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
